### ISSUE TITLE
fix users.md

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/awesome-first-timers#51]
take a look here and fix users.md accordingly
http://anupamdagar.me/awesome-first-timers/users

common errors are no 2 whitespaces after each line
himanshi khandelwal's github username 
look for others by yourself

**Comment by nicolaspascual** [comment]
Working on it

**Comment by Drivez** [comment]
Sendt a PR on this now

**Comment by pulkonet** [comment]
@Anupam-dagar these issues can be resolved at the time of reviewing the PR.

**Comment by Anupam-dagar** [comment]
@pulkonet I know but a cleanup was required.
