### ISSUE TITLE
use grid and cards to display user data in the website.

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/awesome-first-timers#57]

**Comment by LarryBattle** [comment]
Can a framework be pulled in for this? Like [Bootstrap v4](https://getbootstrap.com/docs/4.0/getting-started/introduction/) and [Vuejs v2](https://vuejs.org/v2/guide/)?

**Comment by ericduns** [comment]
I'd like to give this a shot

**Comment by Anupam-dagar** [comment]
@ericduns you should wait till tomorrow, if @LarryBattle doesn't create a PR then you can start working on this.

**Comment by ericduns** [comment]
sounds good

**Comment by LarryBattle** [comment]
:-) It's all yours

**Comment by ericduns** [comment]
@Anupam-dagar I just submitted a pr, let me know what you think, it's fairly "vanilla", but I wanted to keep it that way for now since I don't have that pages actual .css files.
