### ISSUE TITLE
Create a webpage in which users will be displayed.

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/awesome-first-timers#8]
A good template will work

**Comment by Himanshi-Khandelwal** [comment]
@Anupam-dagar I want to work on this. Can you please specify which users r u talking about?

**Comment by devshiva619** [comment]
@Anupam-dagar I would like to work on this.

**Comment by Anupam-dagar** [comment]
@Himanshi-Khandelwal users prent in users.md file.It will be good if you can use jekyll.
@devshiva619 if she doesn't create a PR in 2 days then you can start working on it.

**Comment by iamonuwa** [comment]
@Anupam-dagar am having issues pushing... Am getting `fatal: unable to access 'https://github.com/Anupam-dagar/awesome-first-timers.git/': The requested URL returned error: 403`

![image](https://user-images.githubusercontent.com/6551094/31054166-d63a2e50-a6a4-11e7-8df3-f3153b4fe927.png)

**Comment by Himanshi-Khandelwal** [comment]
@Anupam-dagar  I have not used jekyll.

**Comment by pulkonet** [comment]
@Anupam-dagar I have used Jekyll, do you need instant help with this?

**Comment by pulkonet** [comment]
@iamonuwa How can you push to his repo, fork this repo push your code to it on another branch, then create a pull request.

**Comment by iamonuwa** [comment]
@pulkonet thank you... It worked...

**Comment by Anupam-dagar** [comment]
@Himanshi-Khandelwal since the project is using markdown, it will be much easier to use jekyll than a normal html, @pulkonet you can take up this issue, choose a good and suitable jekyll theme, it will be good if you post the link here before starting to work.

**Comment by pulkonet** [comment]
@Anupam-dagar What about Cayman? It's simplistic and elegant, also you have used it for main project page!
